---
components:
  - ../../base/

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    namespace: observability
    releaseName: observability
    version: 66.3.1
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-default.yaml